blog/urls.py
from django.urls import path
from . import views
from .views import NewPost,UpdatePost,DeletePost

app_name='blog'

urlpatterns = [
    path('',views.blog_home,name='blog_home'),
    path('blog_details/<int:blog_id>/',views.blog_details,name='blog_details'),
    path('new_post/',NewPost.as_view(),name='new_post'),
    path('comment_details/<int:comment_id>/',
         views.comment_detail, name='comment_details'),
    path('comment_all/<int:com_id>/', views.comment_all, name='comment_all'),
    path('new_post/<str:pk>/update/', UpdatePost.as_view(), name='update_post'),
    path('delete_post/<str:pk>/delete/',
         DeletePost.as_view(), name='delete_post'),

         
         
   
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blogger.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('blog.urls',namespace='blog')),
    path('user/', include('user.urls',namespace='user')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.translation import gettext_lazy as _
from django.urls import reverse


class Post(models.Model):
    title = models.CharField(_("title"), max_length=150)
    content = models.TextField(_("content"))
    publish_date = models.DateTimeField(_("publish datae"), auto_now_add=True)
    update_at = models.DateTimeField(_("update post"), auto_now=True)
    created_by = models.ForeignKey(User, verbose_name=_("user_created"), on_delete=models.CASCADE,related_name='created_by')
    photo = models.ImageField(_("photo"), upload_to='images/')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("user:show_post_foruser", args=[self.pk])
        

    class Meta:
        verbose_name = 'post'
        ordering = ('-publish_date',)

class Comment(models.Model):
    name = models.CharField(_("name"), max_length=150)
    email= models.EmailField(_("email"), max_length=254)
    content_commnet = models.TextField(_("comment text"))
    comment = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')
    is_active = models.BooleanField(_("is active"),default=False)
    comment_date = models.DateTimeField(_("comment date"), auto_now_add=True)

    def __str__(self):
        return self.name
    class Meta:
        ordering = ('-comment_date',)  

blog/forms.py
from django import forms
from django.forms import fields
from django.forms.widgets import Textarea

from blog.models import Comment

class CommentForm(forms.ModelForm):
    name = forms.CharField(
        max_length=150, widget=forms.TextInput(attrs={'class': 'wrap-input'}))
    email = forms.EmailField(
        max_length=245, widget=forms.TextInput(attrs={'class': 'wrap-input'}))
    content_commnet = forms.CharField( widget=forms.Textarea(attrs={'class': 'wrap-input'}))

    class Meta:
        model = Comment
        fields = ['name', 'email', 'content_commnet']

blog/views.py
from django.core import paginator
from django.http import request
from django.shortcuts import get_object_or_404, redirect, render
from .models import Comment, Post
from .forms import CommentForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic import CreateView, UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin


def blog_home(request):
    post = Post.objects.all()
    pagintor = Paginator(post, 2)
    page = request.GET.get('page')
    try:
        post = pagintor.page(page)
    except PageNotAnInteger:
        post = pagintor.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_page)
    comment = Comment.objects.all()
    sub = Post.objects.all()
    context = {'posts': post, 'comments': comment, 'sub': sub }
    return render(request, 'blog/index.html', context)


def blog_details(request, blog_id):
    new_comment = CommentForm(request.POST)
    post = get_object_or_404(Post, id=blog_id)
    comment = post.comments.filter(is_active=True)
    if request.method == 'POST':
        new_comment = CommentForm(data=request.POST)
        if new_comment.is_valid():
            new_comment = new_comment.save(commit=False)
            new_comment.comment = post
            new_comment.is_active = False
            new_comment.save()
            messages.success(
                request, 'success send comment , it will be show up as soon as possible')
            return redirect('blog:blog_home')
        else:
            new_comment = CommentForm(request.POST)

    context = {'posts': post, 'comments': comment, 'form': new_comment}
    return render(request, 'blog/blog_details.html', context)


def comment_detail(request, comment_id):
    comment = get_object_or_404(Comment, id=comment_id)
    context = {'comments': comment}
    return render(request, 'blog/comment_details.html', context)


def comment_all(request, com_id):
    post = get_object_or_404(Post, id=com_id)
    comment = Comment.objects.filter(comment__id=com_id)
    paginator = Paginator(comment,2)
    page = request.GET.get('page')
    try:
        comment = paginator.page(page)
    except PageNotAnInteger:
        comment = paginator.page(1)
    except EmptyPage:
        comment = paginator.page(paginator.num_page)        
    context = {'comments': comment, 'post': post}
    return render(request, 'blog/comment_all.html', context)


class NewPost(LoginRequiredMixin,CreateView):
    model=Post
    fields = ['title', 'content', 'photo']
    template_name ='blog/new_post.html'

    def form_valid(self,form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)


class UpdatePost(UserPassesTestMixin,LoginRequiredMixin, UpdateView):
    model=Post
    fields = ['title', 'content', 'photo']
    template_name ='blog/update_post.html'

    def form_valid(self,form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)
    def test_func(self):
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        else:
            return False    

class DeletePost(UserPassesTestMixin,LoginRequiredMixin,DeleteView):
    model = Post 
    success_url ='/'
    def test_func(self) :
        post = self.get_object()
        if self.request.user == post.created_by:
            return True
        return False            

templates/blog/blog_details.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
}
.post img{
    width:100%;
    height: 100%;
    
    object-position: center;
    object-fit: cover;
    display: block;
    border-top-left-radius: .5rem;
    border-top-right-radius: .5rem;
    border-bottom: 4px dotted rgb(202, 202, 202);
    border:6px double #eee;
    
    
}
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin-bottom:3rem
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}

</style>
 <div class="content-post">
      <div class="post">
          <img src="{{posts.photo.url}}" alt="">
          <div class="main-post">
         <h3 class="title"> {{posts.title}}</h3>
        <p class="author">written by : {{posts.created_by}}</p>
        <p class="publish">published at : {{posts.publish_date|date:'Y - M - d'}}</p>
        <p class="text">
        {{posts.content}}<br/><br>
        <a href="{% url 'blog:blog_home' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i>back to home </a>
        </p>
          </div>
      </div>
   
<div class="comments">
            <div class="some_comment">
                <h3>comments of some people have take action</h3>
                {% for comment in comments|slice:3 %}
                <div class="wrap_comment">
                    <h4>{{comment.name}}</h4>
                    <h5>comment at : {{comment.comment_date|date:'Y - M - d'}}</h5>
                    <p>{{comment.content_commnet|truncatechars:80}}
                        <a href="{% url 'blog:comment_details' comment.id %}"><i class="fas fa-arrow-right"></i>See More ...</a>
                    </p>
                </div>
                {% empty %}
                        <div class="wrap_comment">
                    <h4>no comment yet</h4>
                </div>
                {% endfor %}
                <a href="{% url 'blog:comment_all' posts.id %}" class="see-all"> <i class="fas fa-reply-all"></i> see all comment about this atricle <i class="fas fa-reply-all"></i></a>
            </div> 
            <form action="" method='post'>
            {% csrf_token %}
            <div class="wrap-input">
             <label for="username">username</label>
             {{form.name}}
            </div>
            <div class="wrap-input">
             <label for="email">email</label>
                {{form.email}}
                    </div>
            <div class="wrap-input">
             <label for="comment">comment</label>
           {{form.content_commnet}}
            </div>
            <input type="submit" value="Submit Comment" class="submit">
            
        </form> 
      </div>
 
{% endblock content %}

{% block side %}

{% endblock side %}

templates/blog/comment_all.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
}
.post img{
    width:100%;
    height: 100%;
    max-height: 500px;
    object-position: center;
    object-fit: cover;
    display: block;
    border-top-left-radius: .5rem;
    border-top-right-radius: .5rem;
    border-bottom: 4px dotted rgb(202, 202, 202);
    
    
}
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin-bottom:3rem;
    margin-top:2rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
    margin:1rem 0 ;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
</style>
<div class="comments">
    <div class="some_comment">
       <h3>{{post.title}}</h3>
       
        {% for comment in comments %}
        <div class="wrap_comment">
            <h4>{{comment.name}}</h4>
            <h5>comment at : {{comments.comment_date|date:'Y - M - d'}}</h5>
            <p>{{comment.content_commnet}} <br/><br/>
                 <a href="{% url 'blog:blog_home' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i>back to home </a>
            </p>
        </div>
        {% empty %}
         <div class="wrap_comment">
            <h4>no comment yet</h4>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block side %}
<div style="margin-bottom: 5rem;margin-top: 0rem;">
    {% include '../paginations.html' with page=comments %}    
</div>
{% endblock side %}

templates/blog/comment_details.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
}
.post img{
    width:100%;
    height: 100%;
    max-height: 500px;
    object-position: center;
    object-fit: cover;
    display: block;
    border-top-left-radius: .5rem;
    border-top-right-radius: .5rem;
    border-bottom: 4px dotted rgb(202, 202, 202);
    
    
}
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin-bottom:3rem;
    margin-top:2rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
    margin:1rem 0 ;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
</style>
<div class="comments">
    <div class="some_comment">
        <h3>{{comments.comment.title}}</h3>
        <div class="wrap_comment">
            <h4>{{comments.name}}</h4>
            <h5>comment at : {{comments.comment_date|date:'Y - M - d'}}</h5>
            <p>{{comments.content_commnet}} <br/><br/>
                 <a href="{% url 'blog:blog_home' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i>back to home </a>
            </p>
        </div>
    </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}
{% block pagination %}
{% endblock pagination %}

templates/blog/index.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<style>
  .img-user{
    width:75px;
    height: 75px;
    border-radius: 50%;
    align-self: flex-start;
    margin-left: 1rem;
    
  }


  .img-user img{
    width:100%;
    height: 100%;
    border-radius: 50%;
    object-fit: cover;
    display: block;
    border: 4px solid #eee;
  }
  .content-post{
    max-width:700px
  }
</style>
    <div class="content-post">
        {% for post in posts %}
      <div class="post">
         <img src="{{post.photo.url}}" alt="">
         <div class="main-post">
         <div class="img-user">
          <img  src="{{post.created_by.profile.picture.url}}" alt=""/> 
         </div>
          <h3 class="title"> {{post.title}}</h3>
        <p class="author">written by : {{post.created_by}}</p>
        <p class="publish">published at : {{post.publish_date|date:'Y - M - d'}}</p>
        <p class="text">
        {{post.content|truncatewords:30}}<a href="{% url 'blog:blog_details' post.id %}">reade more ...</a>
        </p>
          </div>
 
      </div>
   {% endfor %}
     {% include '../paginations.html' with page=posts %}   
    </div>
 
{% endblock content %}

{% block side %}
    <div class="side-post">
      <h2>make some action</h2>
      <div class="wrap-side">
        <div class="side-conent">
          <h3 class="title">latest post</h3>
          <ul>
            {% for sub in sub|slice:5  %}
            <li><a href="{% url 'blog:blog_details' sub.id %}">{{sub.title}}</a></li>
            {% endfor %}
          </ul>
        </div>
        <div class="side-conent">
          <h3 class="title">latest comments</h3>
          <ul>
            {% for comment in comments|slice:5 %}
            <li><a href="{% url 'blog:comment_details' comment.id %}">{{comment.content_commnet|truncatechars:20}}.... <i class="fa fa-arrow-right" aria-hidden="true"></i></a></li>
          {% endfor %}
          </ul>
        </div>
      </div>
    </div>
   
 
{% endblock side %}

templates/blog/new_post.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>

.wrapper {
    width: 60%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}

.comments{
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    background: #fff;
    padding: 2rem;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin: 0 auto;
    margin-top:3rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
@media screen and (max-width:769px) {
   .wrapper {
    width: 90%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}

</style>
<div class="wrap">
<div class="comments">
            <div class="some_comment">
                <h3>new Post</h3>
            </div> 
            <form action="" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="wrap-input">
             <label for="username">post title</label>
                {{form.title}}
            </div>
            <div class="wrap-input">
                {{form.content}}
            </div>
            <div class="wrap-input">
             <label for="username">choose picture</label>
                {{form.photo}}
            </div>
            <input type="submit" value="create post" class="submit">
        </form> 
      </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}

templates/blog/post_confirm_delete.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>

.wrapper {
    width: 60%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}

.comments{
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    background: #fff;
    padding: 2rem;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin: 0 auto;
    margin-top:3rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
@media screen and (max-width:769px) {
   .wrapper {
    width: 90%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}


</style>
<div class="wrap">
<div class="comments">
            <div class="some_comment">
                <h3>delete Post</h3>
            </div> 
            <form action="" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="wrap-input" style="display:flex;flex-direction: column;justify-content: center;align-items: center; margin-bottom:1rem;">
    
    
                <p>are you sure you want to deletet this <br/> ---- ( {{object.title}} ) ----</p>
            </div>
            <input type="submit" value="confirm delete post" class="submit">
            <a style="margin-top:20px;display:inline-block;" href="{% url 'blog:blog_home' %} ">back to home</a>
        </form> 
      </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}

templates/blog/update_post.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>

.wrapper {
    width: 60%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}

.comments{
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    background: #fff;
    padding: 2rem;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin: 0 auto;
    margin-top:3rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
@media screen and (max-width:769px) {
   .wrapper {
    width: 90%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}

</style>
<div class="wrap">
<div class="comments">
            <div class="some_comment">
                <h3>update Post</h3>
            </div> 
            <form action="" method='post' enctype="multipart/form-data">
            {% csrf_token %}
            <div class="wrap-input">
             <label for="username">post title</label>
                {{form.title}}
            </div>
            <div class="wrap-input">
                {{form.content}}
            </div>
            <div class="wrap-input">
             <label for="username">choose picture</label>
                {{form.photo}}
            </div>
            <input type="submit" value="update post" class="submit">
        </form> 
      </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}