blog/urls.py
from django.urls import path
from . import views
from .views import NewPost,UpdatePost,DeletePost

app_name='blog'

urlpatterns = [
    path('',views.blog_home,name='blog_home'),
    path('blog_details/<int:blog_id>/',views.blog_details,name='blog_details'),
    path('new_post/',NewPost.as_view(),name='new_post'),
    path('comment_details/<int:comment_id>/',
         views.comment_detail, name='comment_details'),
    path('comment_all/<int:com_id>/', views.comment_all, name='comment_all'),
    path('new_post/<str:pk>/update/', UpdatePost.as_view(), name='update_post'),
    path('delete_post/<str:pk>/delete/',
         DeletePost.as_view(), name='delete_post'),

         
         
   
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blogger.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('blog.urls',namespace='blog')),
    path('user/', include('user.urls',namespace='user')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_view
from django.views.generic.base import TemplateView


from . import views

app_name = 'user'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='sign_in'),
    path('logout/', views.log_out, name='log_out'),
    path('active/<uidb64>/<token>/', views.active, name='active'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('all_post_user/<int:post_id>/',
         views.all_post_user, name='all_post_user'),
    path('show_post_foruser/<int:post_id>/',
         views.show_post_foruser, name='show_post_foruser'),

    # reset password here
    path('password_reset/', auth_view.PasswordResetView.as_view(
         template_name='user/registrations/password_reset_form.html',
          email_template_name='user/registrations/password_reset_email.html',
          success_url='password_reset_email_confirm'), name='password_reset'),
         path('password_reset/password_reset_email_confirm/',TemplateView.as_view(
         template_name='user/registrations/password_reset_done.html'),
         name='password_reset_done'),     
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
              template_name='user/registrations/password_reset_confirm.html',
          success_url='/user/password_reset_complete'), name='password_reset_confirm'),

    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(
         template_name='user/registrations/password_reset_complete.html'
          ), name='password_reset_complete')

]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  {% comment %} <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"> {% endcomment %}
  <link rel="stylesheet" href="{% static 'css/main.css' %}">
  <title>blog</title>
</head>
<body>
  <nav class="nav">
    <a href=""><i class="fa fa-book-reader" aria-hidden="true"></i></a>
    <ul>
      <li><a href="{% url 'blog:blog_home' %}">home</a></li>
      <li><a href="">about</a></li>
      <li><a href="">content</a></li>
    </ul>
    <div class="login">
      <ul>

        {% if user.is_authenticated %}
        <li><a href="{% url 'user:profile' user.id %}"> <i class="fas fa-user-edit"></i> profile </a></li>
        <li><a href="{% url 'user:log_out' %}"><i class="fas fa-door-closed"></i>Logout </a></li>
        {% else %}
        <li><a href="{% url 'user:sign_in' %}"><i class="fas fa-door-open"></i> sign in</a></li>&between;
        <li><a href="{% url 'user:sign_up' %}"> <i class="fas fa-user-friends"></i> sign up</a></li>
        {% endif %}
      </ul>
    </div>
  </nav>

  {% comment %} /////////////////// {% endcomment %}

  {% if messages %}
  {% for message in messages %}
    <div class="alert alert-{{messages_tags}}">{{message}}</div>
    {% endfor %}
  {% endif %}
  <div class="wrapper">
{% block content %}
{% endblock content %}
{% block side %}

{% endblock side %}

  </div>
  <footer>
     copy right <i class="fa fa-copyright" aria-hidden="true"></i> 2021
 </footer> 

  <script src="{% static 'js/all.min.js' %}"></script>
</body>
</html>

templates/paginations.html
<style>
  .disabled{
    pointer-events: none;
    display:inline-block;
  }
  .mr{
    margin-right: 5px;
  }
  .ml{
margin-left: 5px;
  }
</style>
   
   <div class="pag">

      {% if page.has_previous %}
       <a href="?page={{page.previous_page_number}}" class="mr"><i class="fa fa-chevron-circle-left"></i></a>
       {% else %}
       <a href="" class="disabled mr"><i class="fa fa-chevron-circle-left"></i></a>
      {% endif %}
      <small>current page ({{page.number}}) from ({{page.paginator.num_pages}}) pages</small>
      {% if page.has_next %}
      <a href="?page={{page.next_page_number}}" class="ml"> <i class="fas fa-chevron-circle-right"></i></a>
      {% else %}
      <a href="" class="disabled ml"><i class="fas fa-chevron-circle-right"></i></a>
      {% endif %}
    </div>