blog/urls.py
from django.urls import path
from . import views
from .views import NewPost,UpdatePost,DeletePost

app_name='blog'

urlpatterns = [
    path('',views.blog_home,name='blog_home'),
    path('blog_details/<int:blog_id>/',views.blog_details,name='blog_details'),
    path('new_post/',NewPost.as_view(),name='new_post'),
    path('comment_details/<int:comment_id>/',
         views.comment_detail, name='comment_details'),
    path('comment_all/<int:com_id>/', views.comment_all, name='comment_all'),
    path('new_post/<str:pk>/update/', UpdatePost.as_view(), name='update_post'),
    path('delete_post/<str:pk>/delete/',
         DeletePost.as_view(), name='delete_post'),

         
         
   
]

blogger/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from blogger.settings import MEDIA_ROOT, MEDIA_URL


urlpatterns = [
    path('', include('blog.urls',namespace='blog')),
    path('user/', include('user.urls',namespace='user')),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_view
from django.views.generic.base import TemplateView


from . import views

app_name = 'user'
urlpatterns = [
    path('sign_up/', views.sign_up, name='sign_up'),
    path('login/', LoginView.as_view(template_name='user/login.html'), name='sign_in'),
    path('logout/', views.log_out, name='log_out'),
    path('active/<uidb64>/<token>/', views.active, name='active'),
    path('profile/<int:user_id>/', views.profile, name='profile'),
    path('update_profile/', views.update_profile, name='update_profile'),
    path('all_post_user/<int:post_id>/',
         views.all_post_user, name='all_post_user'),
    path('show_post_foruser/<int:post_id>/',
         views.show_post_foruser, name='show_post_foruser'),

    # reset password here
    path('password_reset/', auth_view.PasswordResetView.as_view(
         template_name='user/registrations/password_reset_form.html',
          email_template_name='user/registrations/password_reset_email.html',
          success_url='password_reset_email_confirm'), name='password_reset'),
         path('password_reset/password_reset_email_confirm/',TemplateView.as_view(
         template_name='user/registrations/password_reset_done.html'),
         name='password_reset_done'),     
    path('password_reset_confirm/<uidb64>/<token>/',
         auth_view.PasswordResetConfirmView.as_view(
              template_name='user/registrations/password_reset_confirm.html',
          success_url='/user/password_reset_complete'), name='password_reset_confirm'),

    path('password_reset_complete/', auth_view.PasswordResetCompleteView.as_view(
         template_name='user/registrations/password_reset_complete.html'
          ), name='password_reset_complete')

]

user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save

class Profile(models.Model):
    picture = models.ImageField( upload_to='images/',default='images/profile.png')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.user.username


def create_profile(sender,**kwargs):
    if kwargs['created']:
        user_profile = Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile,sender=User)

user/forms.py
from django import forms
from django.contrib.auth import models
from django.contrib.auth.models import User
from django.forms import fields

from .models import Profile

class UpdateProfile(forms.ModelForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'wrap-input', 'readonly': 'readonly'}))
    email = forms.EmailField(widget=forms.TextInput(
        attrs={'class': 'wrap-input', 'readonly': 'readonly'}))
    first_name = forms.CharField(
        widget=forms.TextInput())
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'wrap-input'}))
    class Meta:
        model=User
        fields = ('username','email','first_name','last_name')

class UpdateImage(forms.ModelForm):
    class Meta:
        model=Profile
        fields =('picture',)

user/views.py
from django.core.checks import messages
from django.shortcuts import get_object_or_404, redirect, render
from django.contrib import messages
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.contrib.sites.shortcuts import get_current_site
from django.utils.http import urlsafe_base64_encode,urlsafe_base64_decode
from django.core.mail.message import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes, force_str
from .tokens import generate_token
from blogger.settings import EMAIL_HOST_USER
from django.core.paginator import (Paginator,PageNotAnInteger,EmptyPage)
from .models import Profile
from blog.models import Post
from .forms import UpdateProfile , UpdateImage
from django.contrib.auth.decorators import login_required

def sign_up(request):
    if request.user.is_authenticated:
        return redirect('blog:blog_home')

    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        pass1 = request.POST['pass1']
        pass2 = request.POST['pass2']

        if User.objects.filter(username=username).first():
            messages.error(request,'username has been token .. please choise anther one')
            return redirect('.')

        if User.objects.filter(email=email).exists():
            messages.error(request,'this email is aleady exist')
            return redirect('.')
        if pass1 != pass2:
            messages.error(request,'password does not match')
            return redirect('.')

        user = User.objects.create_user(username=username,email=email,password=pass1) 
        message = f'hello {user.username} \n thanks for visit our site'
        subject ='we have sent a link  an your email '
        email_sent = EMAIL_HOST_USER
        email_recive =[user.email]
        send_mail(subject,message,email_sent,email_recive,fail_silently=True)
        user.is_active=False
        user.save()

        current_site = get_current_site(request)
        email_subject = 'confirm email from @blog'
        message2 = render_to_string('user/confirm_email.html',{
            'user':user.username,
            'domain':current_site.domain,
            'uid':urlsafe_base64_encode(force_bytes(user.pk)),
            'token':generate_token.make_token(user)
        })
        email = EmailMessage(
            email_subject,
            message2,
            EMAIL_HOST_USER,
            [user.email]
        )
        email.fail_silently = True
        email.send()

        messages.success(request,'success created an account ... please check your email for activate your account')       
        return redirect('blog:blog_home')
    return render(request, 'user/sign_up.html')

def log_out(request):
    logout(request)
    return redirect('blog:blog_home')

def active(request,uidb64,token):
    try:
        # force_text
        uid = force_str(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
        if user is not None and generate_token.check_token(user,token):
            user.is_active = True
            user.save()
            login(request,user)
            return redirect('blog:blog_home')
    except:
        pass 
    return render(request,'user/faild_active.html')    

@login_required()
def profile(request,user_id):
    user_id = request.user.id
    profile = get_object_or_404(Profile,user__id=user_id)
    post = Post.objects.filter(created_by__id=user_id)
    paginator = Paginator(post,2)
    page = request.GET.get('page')
    try:
        post = paginator.page(page)
    except PageNotAnInteger:
        post = paginator.page(1)
    except EmptyPage:
        post = paginator.page(paginator.num_pages)    
    post_pag = Post.objects.filter(created_by__id=user_id)
    context = {'profile': profile, 'posts': post, 'post_pag': post_pag}

    return render(request,'user/profile.html',context)


@login_required()
def update_profile(request):
    if request.method == 'POST':
        update_user = UpdateProfile(request.POST,instance=request.user)
        update_img = UpdateImage(request.POST,request.FILES,instance=request.user.profile)
        if update_user.is_valid() and update_img.is_valid():
            update_user.save()
            update_img.save()
            messages.success(request,'success updeted ...')
            return redirect('/user/profile/' + str(request.user.id))
    else:
        update_user = UpdateProfile(instance=request.user)
        update_img = UpdateImage(instance=request.user.profile)
    context ={'update_user':update_user,'update_img':update_img}    

    return render(request,'user/update_profile.html',context)


@login_required()
def all_post_user(request,post_id):
    post_id = request.user.id
    post_user =Post.objects.filter(created_by__id=post_id)
    paginator = Paginator(post_user,2)
    page = request.GET.get('page')
    try:
        post_user = paginator.page(page)
    except PageNotAnInteger:
        post_user = paginator.page(1)
    except EmptyPage:
        post_user = paginator.page(paginator.num_pages)        
    context = {'post_user':post_user}
    return render (request,'user/all_post_user.html',context)


@login_required()
def show_post_foruser(request,post_id):
    post = get_object_or_404(Post,id=post_id)
    return render(request,'user/single_post.html',{'post':post})

templates/user/all_post_user.html
{% extends '../base.html' %}
{% load static %}
{% block content %}
<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
    text-align: center;
    align-content: center;
}
.post img{
    width:100%;
    height: 100%;
    max-height: 500px;
    object-position: center;
    object-fit: cover;
    display: block;
    border-top-left-radius: .5rem;
    border-top-right-radius: .5rem;
    border-bottom: 4px dotted rgb(202, 202, 202);
    
    
}
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
     .update-post{
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
  }
  .update-post a{
      margin-bottom: 1rem;
      border:1px solid #444;
      width: 200px;
      background: #fff;
      padding: 5px 0;
      
  }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin:0 auto;
    text-align:ceneter;
    margin-bottom:3rem;
    margin-top:2rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
    margin:1rem 0 ;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
  .content-post-{
      width:100%;
    border-radius: 30px;
    margin:0 auto;
  }
  .content-post- img{
    width:100%;
    height: 100%;
    
    object-position: center;
    object-fit: cover;
    display: block;
   border-radius: 30px;
   border:6px double #eee;
  }
  .update-post{
      width:100%;
      display: flex;
      align-items: center;
      justify-content: space-around;
  }
    .update-post a{
      margin-bottom: 1rem;
      border:1px solid #444;
      width: 200px;
      background: #fff;
      padding: 5px 0;
      
  }
</style>
<div class="comments">
    <div class="some_comment">
       <h3>{{user.first_name}} {{user.last_name}}</h3>
       
        {% for post in post_user %}
        <div class="content-post-">
            <img src="{{post.photo.url}}" alt="">
        </div>
        <div class="wrap_comment">
            <h4>{{post.title}}</h4>
            <h5>publish at : {{post.publish_date|date:'Y - M - d'}}</h5>
            <p>{{post.content}} <br/><br/>
            </p>
            <div class="update-post">
                <a href="{% url 'blog:new_post' %}">create new post <i class="fas fa-pen-square"></i></a>
                <a href="{% url 'blog:update_post' post.id %}">update post <i class="fas fa-edit"></i></a>
                <a href="{% url 'blog:delete_post' post.id %}">delete post <i class="fas fa-trash"></i></a>
            </div>
        </div>
        {% empty %}
         <div class="wrap_comment">
            <h4>no post yet</h4>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

{% block side %}
<div style="margin-bottom: 5rem;margin-top: 0rem;">
    {% include '../paginations.html' with page=post_user %}    
</div>
{% endblock side %}

templates/user/confirm_email.html
{% autoescape off %}
welcome to our blog
hello : {{user}}
please click the link bellow to activate your account
http://{{domain}} {% url 'user:active' uidb64=uid token=token %}
{% endautoescape %}

templates/user/faild_active.html
{% autoescape off %}
    <h2>Sorry , something going wrong , Try again </h2>
{% endautoescape %}

templates/user/login.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>

.wrapper {
    width: 60%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}

.comments{
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    background: #fff;
    padding: 2rem;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin: 0 auto;
    margin-top:3rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
@media screen and (max-width:769px) {
   .wrapper {
    width: 90%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
.mt-2{
    margin-top:1rem;
    display: inline-block;
    font-size:.9rem;
}

</style>
<div class="wrap">
<div class="comments">
            <div class="some_comment">
                <h3>login page</h3>
                <a href="{% url 'user:sign_up' %}" class="see-all">you have not registered yet ? sign up now <i class="fas fa-user-astronaut"></i></a>
            </div> 
            <form action="" method='post'>
            {% csrf_token %}
            <div class="wrap-input">
             <label for="username">username</label>
            <input type="text" name="username" id='username'>
            </div>
            <div class="wrap-input">
             <label for="comment">password</label>
              <input type="password" name="password" id="password">
            </div>
 
            <input type="submit" value="Sign In" class="submit">
            <a href="{% url 'user:password_reset' %}" class="mt-2">forgotten your password ? get help</a>
        </form> 
      </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}
{% block pagination %}
{% endblock pagination %}

templates/user/profile.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
}
.post{
    border-bottom: 4px dotted rgb(202, 202, 202);
    display: flex;
    align-items: center;
    justify-content: center;
    width:100%;
    padding: 2rem 0;
    
    
} 
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin-bottom:3rem
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
.img{
    display: flex;
    align-items: center;
    justify-content: center;
    width: 100%;
    padding: 2rem;

}
.round-img img{
    width: 100%;
    height: 100%;
    border-radius: 50%;
    display: block;
    object-fit: cover;
    border: 6px double #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
}
.round-img{
    width:200px;
    height:200px;

}
.create{

      margin-bottom: 1rem;
      border:1px solid #444;
      width: 200px;
      background: #fff;
      padding: 5px 0;
      margin:0 auto;
      text-align:center;
      

}

</style>
 <div class="content-post">
      <div class="post">
          <div class="img">
              <div class="round-img" >
                   <img src="{{profile.picture.url}}" alt="">
              </div>
          </div>
                <h3 style="text-transform:capitalize;">{{profile.user.username}}</h3>
                <h4 style="font-weight:300; text-transform:capitalize;">{{profile.user.first_name}} {{profile.user.last_name}}</h4>
                    <h4 style="font-weight:300;">{{profile.user.email}}</h4>
                    <a href="{% url 'user:update_profile' %}"><i class="fas fa-edit"></i>edit Profile</a>
      </div>
<div class="comments">
            <div class="some_comment">
                <h3>you have ({{post_pag.count}}) all posts </h3>
                {% for post in posts %}
                <div class="wrap_comment">
                    <h3>{{post.title}}</h3>
                    <h5>published at : {{post.publish_date|date:'Y - m - d'}} </h5>
                    <p>
                        {{post.content|truncatechars:250}}
                        <a href="{% url 'user:show_post_foruser' post.id %}"><i class="fas fa-arrow-right"></i> read more</a>
                    </p>
                </div>
                {% empty %}
                   <div class="wrap_comment">
                    <h4>you have not type eny post yet</h4>
                </div>
                {% endfor %}
                <a href="{% url 'user:all_post_user' user.id %}" class="see-all"><i class="fas fa-reply-all"></i> see all post you have  <i class="fas fa-reply-all"></i></a>
                <a class="create" href="{% url 'blog:new_post' %}">Create New Post <i class="fas fa-pen-square"></i></a>
            </div> 
      </div>
 
{% endblock content %}

{% block side %}
{% include 'paginations.html' with page=posts %}
{% endblock side %}

templates/user/sign_up.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>

.wrapper {
    width: 60%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}

.comments{
    width: 100%;
    display: grid;
    grid-template-columns: 1fr;
    background: #fff;
    padding: 2rem;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin: 0 auto;
    margin-top:3rem;
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
@media screen and (max-width:769px) {
   .wrapper {
    width: 90%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
    margin: 0 auto;
}
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}

</style>
<div class="wrap">
<div class="comments">
            <div class="some_comment">
                <h3>registered page</h3>
                <a href="{% url 'user:sign_in' %}" class="see-all">aleardy have an account ? sign in <i class="fas fa-user-tag"></i></i></a>
            </div> 
            <form action="" method='post'>
            {% csrf_token %}
            <div class="wrap-input">
             <label for="username">username</label>
             <input type="text" name="username" id="">
            </div>
            <div class="wrap-input">
             <label for="email">email</label>
             <input type="email" name="email" id="">
            </div>
            <div class="wrap-input">
             <label for="pass1">password</label>
          <input type="password" name="pass1" id="">
            </div>
            <div class="wrap-input">
             <label for="pass2">repeat password</label>
        <input type="password" name="pass2" id="">
            </div>
            <input type="submit" value="Sign Up" class="submit">
            
        </form> 
      </div>
</div>
{% endblock content %}

{% block side %}

{% endblock side %}

templates/user/single_post.html
{% extends '../base.html' %}
{% load static %}
{% block content %}

<style>
 .wrapper {
    width: 100%;
    max-width: 1024px;
    height: calc(100% - 60px);
    display: grid;
    grid-template-columns: 1fr;
}
.post img{
    width:100%;
    height: 100%;
    max-height: 500px;
    object-position: center;
    object-fit: cover;
    display: block;
    border-top-left-radius: .5rem;
    border-top-right-radius: .5rem;
    border-bottom: 4px dotted rgb(202, 202, 202);
    
    
}
@media screen and (max-width:769px) {
    .comments{
        flex-direction: column;
    }
         .update-post{
    flex-direction: column;
    justify-content: flex-start;
    align-items: flex-start;
  }
}
.comments{
    width: 100%;
    background: #fff;
    padding: 2rem;
    display: flex;
    justify-content: space-around;
    border-radius: .5rem;
    box-shadow: 1px 3px 5px rgba(0,0,0,0.2);
    margin-bottom:3rem
}
.wrap-input input{
    width: 100%;
    height: 34px;
    margin-bottom: 1rem;
    border: 1px solid rgb(212, 212, 212);
}
.wrap-input textarea{
    width: 100%;
    border: 1px solid rgb(212, 212, 212);
    margin-bottom: 1rem;
    max-width: 800px;
}
label{
    text-transform: capitalize;
}
input{
    font-family: Poppins,sans-serif;
}
.submit{
    width: 100%;
    padding: .5rem 0;
    background: #444;
    color: #fff;
    border: none;
    outline: none;
    cursor: pointer;
    font-size: 1rem;
}
.submit:hover{
   opacity: .9;

}
.some_comment{
    width: 100%;
    display: flex;
    align-items: center;
    flex-direction: column;
}
.some_comment h3{
    text-transform: capitalize;
}
.wrap_comment{
    width: 100%;
    background: #f3f4f5;
    box-shadow: 1px 2px 5px rgba(0,0,0,0.2);
    display: flex;
    align-items: flex-start;
    flex-direction: column;
    margin-right: 1rem;
    padding: 1rem;
    margin-top: .5rem;
    margin-bottom: .5rem;
}
.wrap_comment h4 ,h5{
    text-transform: capitalize;
    font-weight: 500;
    font-size: 1rem;
}
.wrap_comment p{
    font-size: .9rem;
    line-height: 1.4;
}
.see-all{
    margin-top:1rem;
    margin-bottom:1rem;
}
.content-post{
    margin-bottom:2rem;
}
  .update-post{
      width:100%;
      display: flex;
      align-items: center;
      justify-content: space-around;
  }
    .update-post a{
    text-align:center;
      margin-bottom: 1rem;
      border:1px solid #444;
      width: 200px;
      background: #fff;
      padding: 5px 0;
      
  }
</style>
 <div class="content-post">
      <div class="post">
          <img src="{{post.photo.url}}" alt="">
          <div class="main-post">
         <h3 class="title"> {{post.title}}</h3>
        <p class="author">written by : {{post.created_by}}</p>
        <p class="publish">published at : {{post.publish_date|date:'Y - M - d'}}</p>
        <p class="text">
        {{post.content}}<br/><br>
        <a href="{% url 'blog:blog_home' %}"><i class="fa fa-arrow-left" aria-hidden="true"></i>back to home </a>
        </p>
          </div>
              <div class="update-post">
                <a href="{% url 'blog:new_post' %}">create new post <i class="fas fa-pen-square"></i></a>
                <a href="{% url 'blog:update_post' post.id %}">update post <i class="fas fa-edit"></i></a>
                <a href="{% url 'blog:delete_post' post.id %}">delete post <i class="fas fa-trash"></i></a>
            </div>
      </div>

{% endblock content %}

{% block side %}

{% endblock side %}